// Code generated by "stringer -type=PolicyType"; DO NOT EDIT.

package ascache

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Undefined-0]
	_ = x[LRU-1]
	_ = x[LFU-2]
}

const _PolicyType_name = "UndefinedLRULFU"

var _PolicyType_index = [...]uint8{0, 9, 12, 15}

func (i PolicyType) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_PolicyType_index)-1 {
		return "PolicyType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _PolicyType_name[_PolicyType_index[idx]:_PolicyType_index[idx+1]]
}
